## Task 1

In [5]:
import numpy as np

oneDArray = np.arange(1,11)
twoDArray = np.arange(1,10).reshape(3,3)
arrayFromList = np.array([10,20,30,40,50])


array([10, 20, 30, 40, 50])

In [10]:
print(oneDArray.shape,oneDArray.dtype)
print(twoDArray.shape,twoDArray.dtype)
print(arrayFromList.shape,arrayFromList.dtype)


(10,) int64
(3, 3) int64
(5,) int64


# Task 2

In [12]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A**2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


# Task 3


In [14]:
values = np.array([2,4,6,8,10])
print(np.sqrt(values))
print(np.exp(values))
print(np.log(values))
print(np.sum(values))
print(np.cumsum(values))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
30
[ 2  6 12 20 30]


# Task 4

In [19]:
data = np.arange(10,91,10).reshape(3,3)
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))
print(np.min(data))
print(np.max(data))
print(np.mean(data))


[ 60 150 240]
[120 150 180]
10
90
50.0


# Task 5

In [23]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
print(np.mean(marks))
print(np.median(marks))
print(np.var(marks))
print(np.std(marks))
print(np.max(marks)-np.min(marks))

79.25
81.5
134.1875
11.583932838203095
35


# Task 6

In [29]:
print(np.sort(marks))
print(np.percentile(marks,25))
print(np.percentile(marks,50))
print(np.percentile(marks,75))
print(np.percentile(marks,25))
mean_marks = np.mean(marks)
print(np.sum(marks > mean_marks))

[60 66 72 78 85 88 90 95]
70.5
81.5
88.5
70.5
4


# Task 7

In [36]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales),np.min(sales))
print(np.std(sales))
print(np.sum(sales > np.mean(sales)))

10700
1528.5714285714287
2000 900
345.2298849598449
4
